### PR TITLE
remove Gemfile.lock from gitignore to ensure other devs get the same …

### PR DESCRIPTION
**Pull request by stensonb**
…rubies when developing...

This might be why my <code>rake test</code> is failing in this ticket: #18 (this is now fixed by updating .ruby-version to "2.2.0" ; patch included in this PR)

Also, this PR just removes <code>Gemfile.lock</code> from gitignore, it does not add a <code>Gemfile.lock</code> -- maybe somebody can run <code>bundle install ; rake test<code> successfully, and submit another PR for a valid <code>Gemfile.lock</code>.  I would, but I'm unable to run rake test successfully...

### CODE REVIEW

**Comment by jimmidyson** [comment]
As this is a rubygem it's normal to not commit the `Gemfile.lock` file. I'd rather follow that tbh.

As for the ruby version, do you think we should remove from this repo so devs can configure ruby how they want?

**Comment by stensonb** [comment]
I suppose we'll just have to disagree on the <code>Gemfile.lock</code>...fwiw, bundler suggests committing: https://github.com/bundler/bundler/blob/1-0-stable/man/bundle-install.ronn#L248-L253

I would echo their comments by saying (anecdotally) I've run into more problems when using bundler without a Gemfile.lock than with...running "bundle install" on "tested" code without a Gemfile.lock is essentially throwing away all the previous test results (gem dependencies can change, your code can "stay the same", and the tests will, all of a sudden, break...no fun for anybody...especially a newcomer to the project.).

As for the .ruby-version...I'd say the only important part is that if a .ruby-version is specified, it should be used when running unit tests...and, that's not happening here (circle used 2.2.0)

**Comment by jimmidyson** [comment]
I don't think that doesn't really matter/apply for rubygems, as this is, because it's installed more commonly via `gem install` on machines, which uses the gemspec to identify what dependent gems to install too. `bundle install` is used for development of the rubygem only & as such checking in can potentially hide issues with the gem dependencies range specified in the gemspec. I'd rather identify those earlier by contributors such as yourself identifying issues that come up in this way. I know this is a bit annoying but this is one of the problems with the distinction between `bundle install` & `gem install`.

**Comment by jimmidyson** [comment]
Closing for the reasons discussed above.

**Pull request closed without merging**
