### PR TITLE
Allow discarding of raw JSON logs in `log` key; increase verbosity of…

### PR DESCRIPTION
**Pull request by therc**
… client error logging

I don't know Ruby or I'd also log `ssl_options` and `auth_options`.

### CODE REVIEW

**Comment by therc** [comment]
Ping?

**Comment by therc** [comment]
@jimmidyson not sure if this is the right place or the right way to get this looked at/merged.

**Comment by jimmidyson** [comment]
Sorry don't know how I missed this. LGTM but could you add a test for it too please?

**Comment by therc** [comment]
Test added. Twenty seconds of coding, plus a few hours of yak shaving: figuring that I needed ruby2.2, fetching dependencies, getting rake invoked correctly, then errors from VCR that never should have been called, etc. Sorry, as I said, I have never used Ruby before. :-)

**Comment by jimmidyson** [comment]
Don't you be sorry - I'm the one that's sorry for not having a decent contributing guide. I'll add one some time soon.

**Comment by jimmidyson** [comment]
Merged as d4c237e0e2935fd1584889253fdeb3483b579aef & 20e66ac4429021fafc4311ede761459ce44a0c6c.

Thanks! Releasing 0.21.0 in a second - available on rubygems soon.

**Pull request closed without merging**
