### PR TITLE
Reduce kubeclient timeouts to reasonable values

### PR DESCRIPTION
**Pull request by orgads**
The API should be very responsive. If it hangs, it is usually because
something is wrong, and waiting longer won't help.

### CODE REVIEW

**Comment by orgads** [comment]
We had a pod that got a reply for `get_pod`, but timed out (60s) on `get_namespace`. Ideally, I'd prefer to retry 2-3 times on such cases. What do you say?

What's the preferred way to retry?

**Comment by jcantrill** [comment]
> We had a pod that got a reply for `get_pod`, but timed out (60s) on `get_namespace`. Ideally, I'd prefer to retry 2-3 times on such cases. What do you say?

This may be true but what about cases with networks which have high latency?  You may begin to have throughput issues but retrying won't help in these cases. 

> 
> What's the preferred way to retry?

I believe the better way to resolve this issue is to introduce a configuration parameter that allows user's to tweak this setting instead of assuming the defaults provided here fit everyones use case.  These may be fine for defaults but we should also be able to override them.

**Comment by orgads** [comment]
Done (no retry yet).

**Comment by jcantrill** [comment]
Looks good.  Please also update the README

**Comment by orgads** [comment]
> Looks good. Please also update the README

Thank you, done.

**Comment by jcantrill** [comment]
https://rubygems.org/gems/fluent-plugin-kubernetes_metadata_filter/versions/3.1.0

**Comment by orgads** [comment]
Thank you

**Pull request merged**
