### PR TITLE
Don't overwrite the simple namespace/pod/container metadata if we're

### PR DESCRIPTION
**Pull request by a-robinson**
unable to load the more complete metadata.

The first of a couple small changes I plan to make, this one mostly just to make sure my development environment works.

@jimmidyson

### CODE REVIEW

**Comment by jimmidyson** [comment]
Nice catch.

**Comment by jimmidyson** [comment]
Any chance of a unit test?

**Comment by jimmidyson** [comment]
@a-robinson Don't worry - I'll add a unit test & merge at same time.

**Comment by jimmidyson** [comment]
Merged as abc9e506a3c65fabff033850989281d0b1092f1d

**Comment by a-robinson** [comment]
Sorry about the missing unit test! I'll be sure to include one next time

**Comment by jimmidyson** [comment]
No worries - happy that the bug was found & fixed.

**Pull request closed without merging**
