### PR TITLE
Use spec.nodeName for the host value in the metadata map

### LINKED ISSUE #9: host metadata
Im not capturing the host metadata in my local testing environment. Do I need to enable something to get that information?

### PR DESCRIPTION
**Pull request by jchauncey**
fixes #9

### CODE REVIEW

**Comment by jimmidyson** [comment]
I'll fix up test failure & merge in separate PR! Thanks!

**Comment by jimmidyson** [comment]
I pulled your commit into #11 - thanks!

**Comment by jchauncey** [comment]
hey no problem i was startign to look at the tests =)

**Comment by jimmidyson** [comment]
Tagged 0.14.0 - try it out when you get a chance.

**Pull request closed without merging**
