### PR TITLE
WIP: remove namespace_id, container_meta:  image and image_id, labels, hos…

### PR DESCRIPTION
**Pull request by szilvesztersimicza**
remove namespace_id, container_meta:  image and image_id, labels, host, master_url fields from kubernetes metadata

### CODE REVIEW

**Comment by jcantrill** [comment]
@szilvesztersimicza Can you please provide justification for this PR?  You are removing several of the fields which primarily why this plugin exists in the first place.  Minimally, you will need to provide configuration to exclude them, but these changes will break this plugins use with Openshift.

**Comment by richm** [comment]
If you want to reduce the metadata, you should write a record_transformer or record_modifier filter to remove those fields you do not want

**Comment by szilvesztersimicza** [comment]
For my work I do not need these fields. And I can use the record_transformer or filter_record_modifier plugin to remove these fields, but it is more cpu effective to not put these fields into the metadata at all.

But i do not need this PR.  I opened it, to use the CI, but it is outdated (CircleCI 1.0 -> 2.0), and the config process was unsuccessful.
Can Anyone close this PR?
Thanks!

**Comment by richm** [comment]
> For my work I do not need these fields. And I can use the record_transformer or filter_record_modifier plugin to remove these fields, but it is more cpu effective to not put these fields into the metadata at all.

Then you could submit another PR which adds a couple of config parameters: a whitelist of fields to add (_only_ add these fields), and a blacklist (do not add these fields, but add all of the others); then change the code to use these new parameters when adding metadata fields. 

> 
> But i do not need this PR. I opened it, to use the CI, but it is outdated (CircleCI 1.0 -> 2.0), and the config process was unsuccessful.
> Can Anyone close this PR?
> Thanks!

done

**Pull request closed without merging**
