### PR TITLE
Added selector for watch_pods

### PR DESCRIPTION
**Pull request by janario**
Avoid read all the cluster by selecting only the current worknode

I've tried this in a test cluster with 5k pods and 200mb of memory for fluentd

Without this it crashes with `OOMKilled`

Resources should not increase as the cluster scale but as the worknode supports it

---

I still have a problem while limiting `get_pods`, it seems to not take effect

### CODE REVIEW

**Comment by richm** [comment]
basically, fluentd should only be interested in the pods and namespaces on its node - that is, there is no reason for fluentd running on node A to watch all of the pods/namespaces running on node B, node C, etc.

**Comment by richm** [comment]
we will need some sort of test for this too, and an update for the watch related docs (if any, haven't checked)

**Comment by janario** [comment]
@richm ideas on how to create a test for it?

I have to mock the kubernetes api and apply the filter. Do you have some similar test? 

Also can you help me with get_pods with limit? 
(I am not a ruby guy :-) )

**Comment by richm** [comment]
maybe the problem is that this plugin is using a *very* old version of kubeclient?  https://github.com/abonas/kubeclient/blob/v1.1.4/lib/kubeclient/common.rb#L174 does not have support for `limit` afaict

Maybe you could help us find out if we can use the latest kubeclient?  https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/blob/master/fluent-plugin-kubernetes_metadata_filter.gemspec#L24
probably lots of other dependencies that need updating

**Comment by janario** [comment]
@richm sorry for the delay

In the end we decided to disable the `watch` of pods since it was consuming too much memory as the cluster grows

I'm not a ruby developer so it would take too long to me to finish this. Feel free to implements the test, updates and requirements or just leave it open

At least I could exemplify the whole discussion started from https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/issues/170

**Comment by richm** [comment]
We have recently updated the kubeclient version - perhaps this version supports using `watch` with limit?

**Comment by richm** [comment]
closing in favor of https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/189

**Pull request closed without merging**
