### PR TITLE
Reset pod and namespace watch retry count and backoff interval on successful events and add unit tests.

### PR DESCRIPTION
**Pull request by qingling128**
Fixes this:

image

### CODE REVIEW

**Comment by qingling128** [comment]
Side note: Can we do a release after this one is done? The latest commits seem to make a big improvement regarding performance (more details in https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/214#issuecomment-602249297).

**Comment by qingling128** [comment]
Added more unit tests and also apply the change to namespace watches. Ready for review now.

**Comment by jcantrill** [comment]
https://rubygems.org/gems/fluent-plugin-kubernetes_metadata_filter/versions/2.4.5

**Comment by qingling128** [comment]
Thanks @jcantrill !

**Pull request merged**
