### PR TITLE
(Re-)add podIP metadata

### PR DESCRIPTION
**Pull request by stv0g**
This PR pulls in #205 that was reverted in #206

See also #217 which was somehow lost

### CODE REVIEW

**Comment by jcantrill** [comment]
@stv0g please review.  Sorry for the delay

**Comment by maxpain** [comment]
Any updates?

**Comment by jcantrill** [comment]
@stv0g rebased this on `master/HEAD` and the tests fail

**Comment by jcantrill** [comment]
closed in favor of #280

**Pull request closed without merging**
