### PR TITLE
Combined PR for refactoring

### LINKED ISSUE #67: Need access to *namespace* annotations
#31 gets *pod* annotations, but I would like access to *namespace* annotations.  How can I get this information?
$ kubeclt describe namespace NAMESPACE
shows the namespace annotations: e.g.:
kubectl describe namespace default
Name:           default
Labels:         myLabel=abc
Annotations:    myAnnotation=xyz
Status:         Active

No resource quota.

No resource limits.

[NOTE: kubectl annotate namespace NAMESPACE key=value <<--- this adds the annotations...]

### LINKED ISSUE #75: [feature] Add namespace labels
We have metadata on namespaces that we'd love to have in the log entries

### PR DESCRIPTION
**Pull request by mikebryant**
I hope you don't mind, I've taken the liberty of combining a pending PR with my refactoring, and the feature I need, to hopefully speed up merging.

Thus, this:
Fixes #67
Closes #74 
Fixes #75
Closes #76 
Closes #77

### CODE REVIEW

**Comment by disappear89** [comment]
+1 please merge

**Comment by dakky** [comment]
+1 merging would be awesome

**Comment by jimmidyson** [comment]
Thanks @mikebryant! Let me push out a release.

**Comment by jimmidyson** [comment]
Released v0.27.0 - thanks again!

**Comment by disappear89** [comment]
n1 !!

**Pull request merged**
