### PR TITLE
FluentD 1.x API and some logging

### PR DESCRIPTION
**Pull request by arcivanov**
Ruby 2.4.3 added to CI
FluentD 1.x API and dependencies
Debug/trace logging for some visibility into initialization

### CODE REVIEW

**Comment by richm** [comment]
Unfortunately, we still have to support ruby 2.0 for some time due to RHEL7 and CentOS7 dependencies.
I'm not sure how other ruby packages handle support for ruby 2.0 and 2.4 at the same time, which I guess would include support for fluentd 0.12 and 1.0 at the same time.
Do we need a fluentd-1.x branch?  And have separate releases?

**Comment by arcivanov** [comment]
We need fluentd-1.x branch, hence this has been moved to another major version. Usually Fluent plugins have pre-0.14 and post-0.14 versions simultaneously.

https://docs.fluentd.org/v1.0/articles/faq#what-version-of-ruby-does-fluentd-support?
> Fluentd v1.0 works on Ruby 2.1 or later. See v0.12 document for earlier versions.

https://docs.fluentd.org/v1.0/articles/plugin-update-from-v0.12#5.-add-requirements-section
## Requirements

| fluent-plugin-may_awesome | Fluentd     | Ruby   |
|---------------------------|-------------|--------|
| >= 1.0.0                  | >= v0.14.0  | >= 2.1 |
| < 1.0.0                   | >= v0.12.0  | >= 1.9 |

**Comment by arcivanov** [comment]
Alternatively 0.12 version can be frozen for posterity with fixes only and only 1.x+ gets new features. It's really up to the desires of a specific project leadership.

**Comment by jcantrill** [comment]
updated readme in #118

**Comment by jcantrill** [comment]
Does this supercede #65?

**Pull request merged**
