### PR TITLE
Update Dependencies 

### PR DESCRIPTION
**Pull request by joshughes**
Updating dependencies of this plugin so I can install it with other plugins that use more up to date gems.

### CODE REVIEW

**Comment by richm** [comment]
Does this mean the plugin will require ruby > 2.0?

**Comment by joshughes** [comment]
No, it shouldn't I just dropped the ruby-version file... it was committed by mistake

**Comment by edude03** [comment]
I was just coming to ask for this feature! Thanks so much @joshughes !!!

**Comment by jcantrill** [comment]
@joshughes Can you rebase and squash

**Comment by jcantrill** [comment]
@joshughes Something is amiss here.  I thought this PR just updated dependencies.  It appears this PR also includes the stats changes

**Comment by joshughes** [comment]
ya looks like I screwed up in the squash... don't really have time to fix it

**Pull request closed without merging**
