### PR TITLE
loop watch and performance improvement

### PR DESCRIPTION
**Pull request by rockb1017**
This is effort by cisco developers (Stephen & Parjinder).
The impact of these changes are;
* when pod and namespace metadata is updated on kubernetes (ie, namespace being annotated), it gets picked up right away. (I am not sure why version without this patch doesn't pick up instantly) 
* it uses much less CPU.

### CODE REVIEW

**Comment by jcantrill** [comment]
@rockb1017 please see #204.  There's probably room for consolidation

**Comment by rockb1017** [comment]
okay. I can test with #204 and see if we need this PR.

**Comment by jcantrill** [comment]
@rockb1017 is there more to be done here or can we close this PR?

**Comment by rockb1017** [comment]
nope. thank you !

**Pull request closed without merging**
