### PR TITLE
Init watch_retry_count to 0 to avoid nil error.

### PR DESCRIPTION
**Pull request by qingling128**
Fixes https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/issues/222.

### CODE REVIEW

**Comment by desaintmartin** [comment]
Thanks! Is there a estimation for a release containing this fix?

**Comment by colltoaction** [comment]
Just spent the whole day debugging this 😢. Will confirm as soon as I test with v2.4.5.

**Comment by colltoaction** [comment]
I tested with `v2.4.2` and I'm not seeing the nil error. I get a "Killed" message and then everything shuts down, but it's probably a separate issue.

**Comment by iyurev** [comment]
Hi, Has anybody solved that problem?! 
At this time I have to build plugin from master branch for test it?

**Pull request merged**
