### PR TITLE
Lock fluent version for patch release so as not to get unexpected res…

### PR DESCRIPTION
**Pull request by jcantrill**
…ults

Co-authored-by: Jeff Cantrill <jcantril@redhat.chom>

### CODE REVIEW

**Comment by jcantrill** [comment]
@qingling128 I had to rebuild my machine and having issue publishing.  Seems there are updates in the lock file so I'm asking your opinion this change seems reasonable if we are only going to do patch bump?.  Trying to resolve #227

**Comment by jcantrill** [comment]
cc @richm @ewolinetz  thoughts?

**Comment by richm** [comment]
> cc @richm @ewolinetz thoughts?

I'm not sure what is the general guidance for ruby gems publishers, but this seems ok to me.

**Comment by qingling128** [comment]
Looks reasonable to me.

**Comment by mindw** [comment]
@jcantrill, @richm - latest fluentd is 1.10.4. 1.10.0 was released march 24th. 
This change will prevent the plugin from being installed on the latest stable fluentd version. 
Just FYI - thank you for putting the time and effort on maintaining the plugin!

**Comment by jcantrill** [comment]
> @jcantrill, @richm - latest fluentd is 1.10.4. 1.10.0 was released march 24th.
> This change will prevent the plugin from being installed on the latest stable fluentd version.
> Just FYI - thank you for putting the time and effort on maintaining the plugin!

@mindw Understand completely but this is intentional given a patch release of this plugin IMO should not bump to require a minor version change of fluent.  Please consider submitting a patch that would bump the fluent dependency so it can be used on 1.10

**Pull request merged**
