### PR TITLE
Add namespace_annotations when returning annotations

### PR DESCRIPTION
**Pull request by jesseolsen**
This pull request resolves Issue #67.

### CODE REVIEW

**Comment by jimmidyson** [comment]
Could you add a test or two please?

**Comment by jesseolsen** [comment]
Sure.... Updated this Pull Request with 2 namespace annotation tests:
    * test for namespace annotation, matching regex
    * test for no namespace annotations matching regex

**Comment by jimmidyson** [comment]
Sorry could you rebase - just merged something that makes a conflict in your test file...

**Comment by jesseolsen** [comment]
Rebased...

**Pull request closed without merging**
