### PR TITLE
Migrate to use v0.14 API

### PR DESCRIPTION
**Pull request by cosmo0920**
If fluentd plugins use and inherits its class v0.14 API, Fluentd permits to send nanosecond precision time and append time zone information.
If this patches are acceptable for this plugin developers, please review carefully and follow this upgrading from v0.12 (old style) guideline: http://docs.fluentd.org/v0.14/articles/plugin-update-from-v12

Kind regards,

### CODE REVIEW

**Comment by jcantrill** [comment]
@jimmidyson @richm Thoughts on rebaseing this off master and then creating a separate branch for the 0.12.0 stream?  I would propose bumping the version to 1.0 or 2.0 (pending my cache change in #93) to distinguish the 2 releases

**Comment by richm** [comment]
yes - create a separate branch for 0.12, and use master for 0.14

**Comment by richm** [comment]
yes - create a separate branch for 0.12, and use master for 0.14

**Comment by cosmo0920** [comment]
I've rebased this off master.

**Comment by jcantrill** [comment]
updated readme in #118

**Comment by jcantrill** [comment]
@cosmo0920 Can you rebase and update this PR and advise if there is any backporting required.  It seems like there is not.

**Comment by jcantrill** [comment]
Can this be closed in favor of #111 ?

**Comment by jcantrill** [comment]
closing in favor of #111

**Pull request closed without merging**
